# This is an example local.properties file.
# This has no real effect on the project, it's just here to show you
# what your local.properties file should look like.
# Copy this file to your project root and edit the values to match your needs.

# The path to the root of your Android SDK.
# You can find this path by running `sdkmanager --list` in a terminal.
# Make sure you already have the Android SDK installed and the path is correct!
sdk.dir=/path/to/android-sdk

# Whether to compile the Android module for the framework.
# If you set this to true, the Android module will be compiled and
# can be included as a dependency in a test project.
includeAndroid=false
